(in-package #:html)

(defmacro def-edition-page (name edition)
  (let ()
    `(defun ,name ()
       (let ((html-string (make-array 0 :element-type 'character :fill-pointer 0 :adjustable T)))
         (format html-string "~&<html>")
         (format html-string "~&<head>")
         (format html-string "~&<title>~a</title>" (string ',name))
         (format html-string "~&</head>")
         (format html-string "~&<body>")
         (format html-string "~&<h1>Edition header ~a</h1>" (string ',name))
         (format html-string "~&<p>To do content</p>")
         (format html-string "~&</body>")
         (format html-string "~&</html>")
         html-string))))


(defmacro def-participant-page (name participant)
  (let ((participant-points (gethash participant *points* 0)))
    `(defun ,name ()
       (let ((html-string (make-array 0 :element-type 'character :fill-pointer 0 :adjustable T))
             (level (if (> ,participant-points 50) "great" "bad")))
         (format html-string "<html>")
         (format html-string "<head>")
         (format html-string "<title>~a</title>" ,participant)
         (format html-string "</head>")
         (format html-string "<body>")
         (format html-string "<h1>~a's home</h1>" ,participant)
         (format html-string "<p>This is a ~a player.</p><br/>" level)
         (format html-string "<p>This mf has <em>~a</em> points!</p>" ,participant-points)
         (format html-string "</body>")
         (format html-string "</html>")
         html-string))))
