(in-package #:html)

(defmacro def-edition-page (name &body body)
  (let* ((title-form (assoc 'title body :key #'symbol-name :test #'string=))
         (title (second title-form))
         (layout-form (assoc 'layout body :key #'symbol-name :test #'string=))
         (layout (rest layout-form)))
    `(defun ,name ()
       (let ((html-string (make-array 0 :element-type 'character :fill-pointer 0 :adjustable T)))
         (format html-string "~&<html>")
         (format html-string "~&<head>")
         (format html-string "~&<title>~a</title>" ,title)
         (format html-string "~&</head>")
         (format html-string "~&<body>")
         (format html-string "~&<h1>Edition header ~a</h1>" ,title)
         ,@(mapcar #'(lambda (x) `(format html-string "~&~a" ,(expand-edition-forms x))) layout)
         (format html-string "~&</body>")
         (format html-string "~&</html>")
         html-string))))

(defun expand-edition-forms (form)
  (let ((key (symbol-name (first form)))
        (args (rest form)))
    (cond ((string= key 'podium) "<p>PODIUM!</p>")
          ((string= key 'trophies) "<p>TROPHIES TODO!</p>")
          ((string= key 'header) (format nil "<h2>~a</h2>" (first args)))
          (T (error (format nil "Wow what is this? ~a" key))))))

(defmacro def-participant-page (name participant)
  (let ((participant-points (gethash participant *points* 0)))
    `(defun ,name ()
       (let ((html-string (make-array 0 :element-type 'character :fill-pointer 0 :adjustable T))
             (level (if (> ,participant-points 50) "great" "bad")))
         (format html-string "<html>")
         (format html-string "<head>")
         (format html-string "<title>~a</title>" ,participant)
         (format html-string "</head>")
         (format html-string "<body>")
         (format html-string "<h1>~a's home</h1>" ,participant)
         (format html-string "<p>This is a ~a player.</p><br/>" level)
         (format html-string "<p>This mf has <em>~a</em> points!</p>" ,participant-points)
         (format html-string "</body>")
         (format html-string "</html>")
         html-string))))
