baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'descension'
theme = 'typo'

[params]
# Meta description
description = "Descension."

cssPaths = [ "/css/main.css", "/css/fonts.css", "/css/helperClasses.css" ]

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
TODO. I am an Italian Software Engineer with a strong foundation in computer science and a passion for solving complex problems.
I am interested in a range of topics, including algorithms, distributed systems, databases, and information retrieval.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Main menu pages
[[params.menu]]
name = "participants"
url = "/p"

[[params.menu]]
name = "editions"
url = "/e"

