(in-package #:pages)

(defun page-home ()
  (render-html (list :html (list :head (list :title "Descension")
                                 (list :link '(:attrs :href "../../assets/main.css" :rel "stylesheet")))
                     (list :body
                           (list :h1 (list :a '(:attrs :href "/") "Descension"))
                           (list :h2 "Les archives")
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2026") "Édition 2026"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2025") "Édition 2025"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2024") "Édition 2024"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2023") "Édition 2023"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2022") "Édition 2022"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2021") "Édition 2021"))
                           (list :div '(:attrs :class "edition-link") (list :a '(:attrs :href "/e/2019") "Édition 2019"))))))
